trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Dummy Print Statement'

- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
    outputFormat: 'sarif'

- task: Semmle@0
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'javascript'
    includeNodeModules: true
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
  env:
    SYSTEM_ACCESSTOKEN: $(PATToken)
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'